### ISSUE TITLE
[Bug] GenericWeather complication stuck on Celsius 

### ISSUE THREAD

**Issue by ThatOneCalculator** [pacjo/SmartspacerPlugins#1]
The target works fine, but trying to change the complication units to Fahrenheit doesn't work, as it's stuck on Celsius.

**Comment by pacjo** [comment]
Good catch! I messed up variables when working on configuration activities. This one should fix it: [app-genericweather-debug.zip](https://github.com/pacjo/SmartspacerPlugins/files/13805571/app-genericweather-debug.zip)

**Comment by ThatOneCalculator** [comment]
Yep, that fixes it! Thank you!

**Comment by pacjo** [comment]
Thanks, closing then. Code is already up: [9b20279](https://github.com/pacjo/SmartspacerPlugins/commit/9b20279c70e40aaa6032009606b8eb1e88ce987b), I will publish official update later.
