### ISSUE TITLE
Use system 24-hour format setting

### ISSUE THREAD

**Issue by D3SOX** [pacjo/SmartspacerPlugins#15]
I have my system set to use a 12-hour time format but the weather plugin doesn't respect that

**Comment by pacjo** [comment]
I know, there's a `TODO` in the code. I just didn't get around to it.

**Comment by pacjo** [comment]
Can you try this?

[app-genericweather-release.zip](https://github.com/user-attachments/files/16816151/app-genericweather-release.zip)

**Comment by D3SOX** [comment]
![Screenshot_20240830-172754_cropped.png](https://github.com/user-attachments/assets/976043b2-6de0-4a44-a6eb-06a16b759f78)

![Screenshot_20240830-172629_cropped.png](https://github.com/user-attachments/assets/0ea03d64-45a4-4d5d-b545-2304cdca1853)

Seems to work fine for the temperature but I think it broke the sun times

**Comment by pacjo** [comment]
[app-genericweather-release.zip](https://github.com/user-attachments/files/16819420/app-genericweather-release.zip)

Good catch, this should fix it. There was a leftover multiplication since weather gives timestamps in seconds, but `System.currentTimeMillis()` is in, well... milliseconds.

**Comment by pacjo** [comment]
@D3SOX, did the fix work?

**Comment by D3SOX** [comment]
Nope it was 20:06 before and now it shows 6:45 instead of 8:06

**Comment by pacjo** [comment]
Are you sure you're using the version from the second zip? It works fine for me. (just in case it contains old version, I'm attaching latest with some other changes below).

[app-genericweather-release.zip](https://github.com/user-attachments/files/16833426/app-genericweather-release.zip)

Also now that I look at this it really could use a AM/PM indicator. What do you think?

**Comment by D3SOX** [comment]
Not sure what the problem was but now with this version it works fine

**Comment by pacjo** [comment]
> If you're adding an AM/PM indicator I would make it configurable as I personally don't need it.

Sure.

> Not sure what the problem was but now with this version it works fine.

Awesome, closing then.
