### ISSUE TITLE
duolingo bug

### ISSUE THREAD

**Issue by gaosunhao** [pacjo/SmartspacerPlugins#17]
![Screenshot_20240928-143956_Pixel 启动器](https://github.com/user-attachments/assets/30377f7e-50f8-4811-9a0c-8588729a3806)
Recently, there is a display bug in the plugin of Duolingo, occasionally the picture on the left side will display normally, but most of the time there is a very blurry phenomenon
My device is Redmi K60, Android 14, evolution X rom

**Comment by pacjo** [comment]
https://github.com/pacjo/SmartspacerPlugins/issues/16
