### ISSUE TITLE
[Feature request] option to use Breezy Weather/Geometric Weather icon packs and/or Material Icons 

### ISSUE THREAD

**Issue by ThatOneCalculator** [pacjo/SmartspacerPlugins#2]
Right now for Breezy Weather, I use the Pixel icon pack, but that's not reflected in the complication. Being able to either use that or the material icons representing the weather condition would be great for visual consistency. 

Complication:

![Screenshot_20240101-121907.png](https://github.com/pacjo/SmartspacerPlugins/assets/44733677/0202f9ea-ea4f-49bc-a871-b045330ddd11)

Breezy Weather widget:

![Screenshot_20240101-121928.png](https://github.com/pacjo/SmartspacerPlugins/assets/44733677/62f38c30-c2a6-46d3-b53f-b3913007dfde)

Breezy Weather UI:

![Screenshot_20240101-121905.png](https://github.com/pacjo/SmartspacerPlugins/assets/44733677/23d82e5f-5655-4772-84f5-d89449e2baa9)

**Comment by ThatOneCalculator** [comment]
Material weather icons (most visually consistent with other complications): https://fonts.google.com/icons?icon.query=weather

![Screenshot_20240101-122311.png](https://github.com/pacjo/SmartspacerPlugins/assets/44733677/6165a1df-84c7-46c9-b2c2-441dcc650850)

**Comment by CoelacanthusHex** [comment]
I use Round iconpack for Breezy Weather and meet this inconsistency issue. If it's too difficult to support Breezy Weather/Geometric Weather icon packs, use Material weather icons is an acceptable solution.
FYI, iconpack document is https://github.com/breezy-weather/breezy-weather-icon-packs/blob/main/INSTRUCTIONS.md

**Comment by pacjo** [comment]
> FYI, iconpack document is https://github.com/breezy-weather/breezy-weather-icon-packs/blob/main/INSTRUCTIONS.md

I know about that, thanks. I even talked with maintainer of Breezy and he did point me to the important parts of icon pack logic, but I wasn't able to implement it.

Anyway, I'd love to add this in the future, so this issue is staying open for now.

**Comment by pacjo** [comment]
...and to make icons consistent here's google icons icon pack for breezy: [app-release.zip](https://github.com/user-attachments/files/16984030/app-release.zip)

**Comment by pacjo** [comment]
I'll ping you a bit more, here's a much more polished version with new configuration activities and mostly fixed refreshes. I don't know if other issues will be fixed before the next release.

[app-genericweather-release.zip](https://github.com/user-attachments/files/16997980/app-genericweather-release.zip)

**Let me know if you have encountered any issues.**

**Comment by ThatOneCalculator** [comment]
Works!!
 

![Screenshot_20240913-154809.png](https://github.com/user-attachments/assets/ada1f232-be8c-4f1a-be9b-3fef76161769)
