### ISSUE TITLE
[Feature request] Option to hide Duolingo if lesson completed

### ISSUE THREAD

**Issue by CennoxX** [pacjo/SmartspacerPlugins#5]
Add an option to the Duolingo plugin, to hide the target when the lesson of the day has been completed.
Thanks for the great plugins!

**Comment by pacjo** [comment]
Ok, let's try this: 
[app-duolingo-release.zip](https://github.com/pacjo/SmartspacerPlugins/files/13980831/app-duolingo-release.zip)

**Comment by CennoxX** [comment]
> Ok, let's try this: [app-duolingo-release.zip](https://github.com/pacjo/SmartspacerPlugins/files/13980831/app-duolingo-release.zip)

Great, this works! Yesterday I completed the lesson and it got hidden, today it is there again.

**Comment by pacjo** [comment]
Ok, I pushed the source changes, and updated plugin.json. It should appear in the official repository soon.

**Comment by rodrigoswz** [comment]
Is possible to force dismiss? Unfortunately, this hide option automatically doesn't always work. This randomly stops working.

**Comment by pacjo** [comment]
There's no such option. Duolingo seems to change the strings I use to detect that so this requires manual intervention.

As you can see the project isn't very actively maintained right now. I plan to work on it, but there's no timeline. PRs always welcome.
